### ISSUE TITLE
Add Twitter Cards

### ISSUE THREAD

**Issue by khalidabuhakmeh** [ritterim/ritterim.github.io#196]
![image](https://cloud.githubusercontent.com/assets/228256/21059727/e4619238-be11-11e6-9a38-1159afd4ff81.png)

MozBar says we don't have them

**Comment by kendaleiv** [comment]
Assigned @khalidabuhakmeh as he appears to be working on this.

**Comment by kendaleiv** [comment]
#197 was merged for this.
