### ISSUE TITLE
Open source this blog?

### ISSUE THREAD

**Issue by kendaleiv** [ritterim/ritterim.github.io#32]
Do we want to open source the blog and make it available for corrections, post suggestions as issues, etc?

As an example, Phil Haack has his blog as a public repository: https://github.com/Haacked/haacked.com / http://haacked.com/

**Comment by ScottSchwalm** [comment]
Close this or is https://github.com/ritterim/ritterim.github.io/issues/32#issuecomment-248020671 going to happen?

**Comment by khalidabuhakmeh** [comment]
It just happened :P
