### ISSUE TITLE
add pets page 

### ISSUE THREAD

**Issue by hougasian** [ritterim/ritterim.github.io#455]
## 🔧 Enhancement Request 

Create a pets page for anyone who would like their pet(s) posted. Similar to https://petsofnetlify.com/

- use [fa-paw](https://fontawesome.com/icons/paw?style=solid) as a nav icon that links to this new page. 
- same page structure (header, nav, footer)
- remember, this site uses [semantic UI](https://semantic-ui.com/introduction/getting-started.html)
  - https://semantic-ui.com/views/card.html#fluid-card
  - https://semantic-ui.com/views/card.html#column-count

## Who is asking for the feature?

#frontend

## What business problem is this hoping to solve?

nothing.

**Comment by Sobieck** [comment]
![IMG_4184](https://user-images.githubusercontent.com/6256765/102791573-d1c7e700-436c-11eb-9213-e560d2a6b79c.JPG)

**Comment by Sobieck** [comment]
![IMG_2854](https://user-images.githubusercontent.com/6256765/102792595-549d7180-436e-11eb-954d-0ac944cf33f1.jpg)
![IMG_2679](https://user-images.githubusercontent.com/6256765/102792599-56673500-436e-11eb-82d6-6ef28ffdabd2.jpg)

**Comment by czy5074** [comment]
![mmexport1607815374155](https://user-images.githubusercontent.com/27984559/102793990-ac40da80-4378-11eb-8aab-6d67b0b3f9e3.jpg)
Left: Pudding 🍮; Middle: Fries 🍟; Right: Noemie 

![mmexport1604871592289](https://user-images.githubusercontent.com/27984559/102794238-13f72580-4379-11eb-84f2-ab14167ca0ba.jpg)
![mmexport1607015643991](https://user-images.githubusercontent.com/27984559/102794261-1eb1ba80-4379-11eb-9832-46cc836b1cc3.jpg)
![mmexport1607015630574](https://user-images.githubusercontent.com/27984559/102794279-26715f00-4379-11eb-85be-b5d4b016cd6b.jpg)
![mmexport1604870743029](https://user-images.githubusercontent.com/27984559/102794352-430d9700-4379-11eb-84b5-1f0266fe491c.jpg)

**Comment by hougasian** [comment]
## Echo
![IMG_3550](https://user-images.githubusercontent.com/6231956/102794722-c4652980-4379-11eb-9fbb-8fefc18fa1ff.JPG)
## Lars
![IMG_0822](https://user-images.githubusercontent.com/6231956/102794731-c7f8b080-4379-11eb-90d2-1cd8fc46c5e7.JPG)
## Lucy
![IMG_0247](https://user-images.githubusercontent.com/6231956/102794740-c9c27400-4379-11eb-897d-6262bd8f8a91.JPG)

**Comment by mrtrimble** [comment]
## Sunshine
![PXL_20200802_150223530 PORTRAIT](https://user-images.githubusercontent.com/5217768/102794959-173ee100-437a-11eb-9ba1-cd53d4205ba0.jpg)

## T3
![PXL_20201119_144926181 PORTRAIT](https://user-images.githubusercontent.com/5217768/102795009-27ef5700-437a-11eb-8874-ad0402d66b88.jpg)

## Rylie
![PXL_20201104_151314435 PORTRAIT](https://user-images.githubusercontent.com/5217768/102795019-2c1b7480-437a-11eb-8cba-67c05d620839.jpg)

**Comment by natakurus** [comment]
## Martin

![Martin](https://user-images.githubusercontent.com/25621042/102807942-9689e000-438d-11eb-888d-8ced83d1a5f4.jpg)

**Comment by jpvicari** [comment]
For now...
### Manny
![manny](https://user-images.githubusercontent.com/10562755/102820359-1d958300-43a3-11eb-814a-ace93459d5dd.jpg)

**Comment by tedk13** [comment]
haha Martin is a little stud, @natakurus

**Comment by tedk13** [comment]
## Odin

![IMG_0830_Original](https://user-images.githubusercontent.com/5313708/102820747-c217c500-43a3-11eb-9a8b-b26e72768fd8.jpg)
![IMG_3437](https://user-images.githubusercontent.com/5313708/102820754-c80da600-43a3-11eb-889b-75c417f487ab.jpg)
![IMG_0071](https://user-images.githubusercontent.com/5313708/102820784-d5c32b80-43a3-11eb-99c1-52816854d38b.JPG)

**Comment by hougasian** [comment]
ok! the middle one's perfect @tedk13 !! 😂

**Comment by bwarner22** [comment]
Oscar & Jazzmin
![60014044239__E1543C2F-1B7F-4397-8288-24518779390F](https://user-images.githubusercontent.com/1625929/102821291-d3150600-43a4-11eb-8611-44fa965b36b6.jpg)
![IMG_4093](https://user-images.githubusercontent.com/1625929/102821297-d5776000-43a4-11eb-9f22-6ba6cb92de1a.jpg)
![IMG_5223](https://user-images.githubusercontent.com/1625929/102821300-d6a88d00-43a4-11eb-8f1e-bde0824774b9.jpg)

**Comment by hougasian** [comment]
@bwarner22 perfect!

**Comment by billbogaiv** [comment]
## Bella
![bella1](https://user-images.githubusercontent.com/3382469/102932970-513ddf00-446f-11eb-8c67-538659469311.jpeg)

## Harper
![harper1](https://user-images.githubusercontent.com/3382469/102932985-58fd8380-446f-11eb-8bce-4d870ed1e556.jpeg)

**Comment by Azbury** [comment]
## Yuumi

![yuumi](https://user-images.githubusercontent.com/18554928/103806169-a1e23a00-5022-11eb-84a2-55a504e57441.jpg)

## Momo

![momo](https://user-images.githubusercontent.com/18554928/103806187-a7d81b00-5022-11eb-87c5-1266fb251c3c.jpg)

**Comment by hougasian** [comment]
Closing. https://rimdev.io/the-pets-of-rimdev/
